const apiUrl = "http://18.218.152.243:8080/";
export default {
    signUp: "https://family-one.auth0.com/api/v2/users",
    getToken:'https://family-one.auth0.com/oauth/token',
    login: "https://family-one.auth0.com/passwordless/start",
    phone: "https://api.authy.com/protected/json/phones/verification/start",
    profile: apiUrl + "api/profile",
    updateProfile: apiUrl + "api/profile",
    update_profile_image: apiUrl + "api/updateProfileImage",
    contactList: apiUrl + "contactapi",
    updateContact: apiUrl + "contactapi/update_contact",
    addContact: apiUrl + "contactapi/add_contact",
    updatePassword: apiUrl + "api/updatePassword",
    getServerChallenegeData: apiUrl + "challangeapi/getServerChallenegeData",
    createChallange: apiUrl + "challangeapi/create",
    lobby: apiUrl + "challangeapi/lobby",
    challangeInfo: apiUrl + "challangeapi/challenge_detail",
    deleteChallange: apiUrl + "challangeapi/deleteChallange",
    playChallange: apiUrl + "play_challangeapi",
    inbox: apiUrl + "inboxapi",
    editChallange: apiUrl + "challangeapi/edit_challange",
    compose: apiUrl + "inboxapi/compose",
    publishChallange: apiUrl + "challangeapi/publishChallange",
    listEmail: apiUrl + "inboxapi/listEmail",
    mail: apiUrl + "inboxapi/mail",
    answerDetail: apiUrl + "answer_detail_api",
    homeapi: apiUrl + "homeapi/home",
    forgotpasswordapi: apiUrl + "forgotpasswordapi/sendemail",
    starChallenge: apiUrl + "challangeapi/star_challenge_detail",
    deletecontact: apiUrl + "contactapi/delete_contact",
    editanswer: apiUrl + "answer_detail_api/edit_answer"
}